import React, { useMemo, useState } from "react";
import { FileText, ShieldCheck, Search, Lock, AlertTriangle, CheckCircle2, Scale, History, Users, ClipboardList, Eye } from "lucide-react";

const policies = [
  { id: "POL-001", title: "Student Data Access Policy", domain: "Data", owner: "Compliance OS", status: "Approved", risk: "Low", coverage: 97, updated: "2026-06-10", appliesTo: "All Staff" },
  { id: "POL-004", title: "Document Handling & Retention Policy", domain: "Documents", owner: "Compliance OS", status: "Approved", risk: "Low", coverage: 93, updated: "2026-06-06", appliesTo: "Counselor + Admin" },
  { id: "POL-009", title: "Payment Verification Policy", domain: "Finance", owner: "Finance OS", status: "Live", risk: "Medium", coverage: 88, updated: "2026-06-07", appliesTo: "Finance Team" },
  { id: "POL-013", title: "Automation Approval Policy", domain: "Automation", owner: "Automation OS", status: "Review", risk: "High", coverage: 79, updated: "2026-06-05", appliesTo: "Managers" },
  { id: "POL-018", title: "Partner Communication Standard", domain: "Partner", owner: "Partner OS", status: "Draft", risk: "Medium", coverage: 71, updated: "2026-06-04", appliesTo: "Partner Team" }
];

function Metric({ icon: Icon, label, value, note }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="text-blue-600"/><div className="mt-3 text-2xl font-black">{value}</div><div className="text-sm font-bold">{label}</div><div className="text-xs text-slate-500">{note}</div></div>; }
function Status({ value }) { const tone = value === "Approved" || value === "Live" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : value === "Review" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-slate-200 bg-slate-50 text-slate-600"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${tone}`}>{value}</span>; }
function Risk({ value }) { const tone = value === "High" ? "border-red-200 bg-red-50 text-red-700" : value === "Medium" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${tone}`}>{value}</span>; }

export default function PolicyKnowledgeHub({ compact = false }) {
  const [query, setQuery] = useState("");
  const [domain, setDomain] = useState("All");
  const domains = ["All", ...new Set(policies.map(p => p.domain))];
  const visible = useMemo(() => policies.filter(p => (domain === "All" || p.domain === domain) && (!query || Object.values(p).join(" ").toLowerCase().includes(query.toLowerCase()))), [query, domain]);
  const avgCoverage = Math.round(policies.reduce((s,p)=>s+p.coverage,0)/policies.length);

  return <div className="space-y-6">
    <div className="grid gap-4 md:grid-cols-4"><Metric icon={FileText} label="Policies" value={policies.length} note="Controlled documents"/><Metric icon={ShieldCheck} label="Approved/Live" value={policies.filter(p=>p.status==='Approved'||p.status==='Live').length} note="Ready policies"/><Metric icon={AlertTriangle} label="High Risk" value={policies.filter(p=>p.risk==='High').length} note="Requires executive review"/><Metric icon={Scale} label="Coverage" value={`${avgCoverage}%`} note="Policy readiness"/></div>
    <div className="grid gap-6 xl:grid-cols-[1.7fr_1fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black">Policy Knowledge Hub</h2><p className="text-sm text-slate-500">Compliance-ready policy center for data, documents, payments, automation approvals and partner standards.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search policies" className="rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none"/></div><select value={domain} onChange={(e)=>setDomain(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none">{domains.map(d=><option key={d}>{d}</option>)}</select></div></div>
      <div className="mt-5 overflow-hidden rounded-2xl border border-slate-100"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Policy</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Coverage</th><th className="px-4 py-3">Applies To</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3"><div className="font-black">{p.title}</div><div className="text-xs text-slate-500">{p.id} · {p.domain} · {p.owner} · Updated {p.updated}</div></td><td className="px-4 py-3"><Status value={p.status}/></td><td className="px-4 py-3"><Risk value={p.risk}/></td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="h-2 w-20 rounded bg-slate-100"><div className="h-2 rounded bg-slate-900" style={{width:`${p.coverage}%`}}/></div><span className="text-xs font-bold">{p.coverage}%</span></div></td><td className="px-4 py-3 text-slate-500">{p.appliesTo}</td></tr>)}</tbody></table></div></div>
      <div className="space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Compliance Controls</h3><div className="mt-4 space-y-3">{[{i:Lock,t:"Access controls",n:"Role-based visibility"},{i:History,t:"Review history",n:"Every policy has owner/date"},{i:Eye,t:"Audit visibility",n:"Ready for executive audit"},{i:ClipboardList,t:"Approval queue",n:"1 high-priority review"}].map(({i:Icon,t,n})=><div key={t} className="flex gap-3 rounded-2xl bg-slate-50 p-3"><Icon size={16} className="text-blue-600"/><div><div className="font-bold text-sm">{t}</div><div className="text-xs text-slate-500">{n}</div></div></div>)}</div></div>{!compact && <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Policy Actions</h3><div className="mt-4 space-y-3"><button className="w-full rounded-2xl bg-slate-900 p-3 text-sm font-bold text-white">Open Approval Queue</button><button className="w-full rounded-2xl border border-slate-200 p-3 text-sm font-bold text-slate-700">Export Compliance Pack</button></div></div>}</div>
    </div>
  </div>;
}
