import React, { useMemo, useState } from "react";
import { Landmark, Search, Globe2, CalendarClock, BadgeCheck, AlertTriangle, GraduationCap, FileText, BarChart3, MapPin } from "lucide-react";

const universityRules = [
  { id: "UNI-UK-001", university: "University of Hertfordshire", country: "UK", intake: "Sep 2026", ruleType: "Deposit", requirement: "Deposit proof required before CAS preparation.", status: "Active", confidence: 94, owner: "UK Desk", updated: "2026-06-10" },
  { id: "UNI-UK-002", university: "Birmingham City University", country: "UK", intake: "Sep 2026", ruleType: "English", requirement: "MOI/IELTS rules depend on course and prior institution.", status: "Review", confidence: 81, owner: "UK Desk", updated: "2026-06-07" },
  { id: "UNI-CA-001", university: "University Canada West", country: "Canada", intake: "Jan 2027", ruleType: "Offer", requirement: "Academic documents and passport required for initial assessment.", status: "Active", confidence: 89, owner: "Canada Desk", updated: "2026-06-06" },
  { id: "UNI-AUS-001", university: "Deakin University", country: "Australia", intake: "Feb 2027", ruleType: "GTE", requirement: "Genuine student narrative and financial evidence required before lodgement.", status: "Draft", confidence: 73, owner: "Australia Desk", updated: "2026-06-04" }
];

function Stat({ icon: Icon, label, value, note }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="text-blue-600"/><div className="mt-3 text-2xl font-black">{value}</div><div className="text-sm font-bold">{label}</div><div className="text-xs text-slate-500">{note}</div></div>; }
function Badge({ status }) { const tone = status === "Active" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : status === "Review" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-slate-200 bg-slate-50 text-slate-600"; return <span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${tone}`}>{status}</span>; }

export default function UniversityKnowledgeHub({ compact = false }) {
  const [country, setCountry] = useState("All");
  const [query, setQuery] = useState("");
  const countries = ["All", ...new Set(universityRules.map((x) => x.country))];
  const filtered = useMemo(() => universityRules.filter((rule) => (country === "All" || rule.country === country) && (!query || Object.values(rule).join(" ").toLowerCase().includes(query.toLowerCase()))), [country, query]);

  return <div className="space-y-6">
    <div className="grid gap-4 md:grid-cols-4"><Stat icon={Landmark} label="Rule Records" value={universityRules.length} note="University conditions"/><Stat icon={Globe2} label="Countries" value={countries.length - 1} note="Destination coverage"/><Stat icon={BadgeCheck} label="Active Rules" value={universityRules.filter(x=>x.status==='Active').length} note="Ready for planning"/><Stat icon={AlertTriangle} label="Review Needed" value={universityRules.filter(x=>x.status!=='Active').length} note="Refresh queue"/></div>
    <div className="grid gap-6 xl:grid-cols-[1.7fr_1fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-black">University Knowledge Hub</h2><p className="text-sm text-slate-500">University-specific rules for offers, deposits, intakes, English requirements and planning decisions.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search university rules" className="rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none"/></div><select value={country} onChange={(e)=>setCountry(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none">{countries.map(c=><option key={c}>{c}</option>)}</select></div></div>
      <div className="mt-5 overflow-hidden rounded-2xl border border-slate-100"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">University</th><th className="px-4 py-3">Rule</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Owner</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(rule=><tr key={rule.id} className="hover:bg-slate-50"><td className="px-4 py-3"><div className="font-black">{rule.university}</div><div className="text-xs text-slate-500">{rule.country} · {rule.intake} · {rule.id}</div></td><td className="px-4 py-3"><div className="font-semibold">{rule.ruleType}</div><div className="max-w-md text-xs text-slate-500">{rule.requirement}</div></td><td className="px-4 py-3"><Badge status={rule.status}/></td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="h-2 w-20 rounded bg-slate-100"><div className="h-2 rounded bg-slate-900" style={{width:`${rule.confidence}%`}}/></div><span className="text-xs font-bold">{rule.confidence}%</span></div></td><td className="px-4 py-3 text-slate-500">{rule.owner}</td></tr>)}</tbody></table></div></div>
      <div className="space-y-6"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Destination Intelligence</h3><div className="mt-4 space-y-3">{countries.filter(c=>c!=="All").map(c=><div key={c} className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center gap-2 font-bold"><MapPin size={15}/>{c}</div><div className="text-xs text-slate-500">{universityRules.filter(x=>x.country===c).length} knowledge records</div></div>)}</div></div>{!compact && <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Planning Signals</h3><div className="mt-4 grid gap-3"><div className="rounded-2xl bg-blue-50 p-3 text-sm text-blue-800"><CalendarClock size={16}/> Sep 2026 UK intake requires deadline refresh.</div><div className="rounded-2xl bg-amber-50 p-3 text-sm text-amber-800"><FileText size={16}/> English rule confidence below 85% for one university.</div><div className="rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-800"><BarChart3 size={16}/> Active rule coverage is stable for priority destinations.</div></div></div>}</div>
    </div>
  </div>;
}
